import { MarketSnapshot } from "@/lib/types";

const seededSnapshots: MarketSnapshot[] = [
  {
    pair: "EUR/USD",
    price: 1.0834,
    session: "London",
    spreadPips: 0.8,
    atrPips: 22,
    trendStrength: 84,
    momentum: 78,
    pullbackQuality: 82,
    volatilityScore: 72,
    liquidityScore: 91,
    newsRisk: 24,
    directionBias: "BUY",
    support: 1.0814,
    resistance: 1.0878,
    source: "Seeded market snapshot",
  },
  {
    pair: "GBP/USD",
    price: 1.2678,
    session: "London",
    spreadPips: 1.2,
    atrPips: 31,
    trendStrength: 79,
    momentum: 74,
    pullbackQuality: 75,
    volatilityScore: 68,
    liquidityScore: 86,
    newsRisk: 33,
    directionBias: "BUY",
    support: 1.2642,
    resistance: 1.2736,
    source: "Seeded market snapshot",
  },
  {
    pair: "USD/JPY",
    price: 153.46,
    session: "Overlap",
    spreadPips: 1.1,
    atrPips: 28,
    trendStrength: 77,
    momentum: 65,
    pullbackQuality: 72,
    volatilityScore: 63,
    liquidityScore: 88,
    newsRisk: 41,
    directionBias: "SELL",
    support: 152.94,
    resistance: 153.88,
    source: "Seeded market snapshot",
  },
  {
    pair: "AUD/USD",
    price: 0.6548,
    session: "Tokyo",
    spreadPips: 1.5,
    atrPips: 19,
    trendStrength: 61,
    momentum: 58,
    pullbackQuality: 55,
    volatilityScore: 52,
    liquidityScore: 64,
    newsRisk: 37,
    directionBias: "SELL",
    support: 0.6531,
    resistance: 0.6572,
    source: "Seeded market snapshot",
  }
];

export function getMarketSnapshots() {
  return seededSnapshots;
}
